name: Integration testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.5
    - name: Build
      run: cd examples/demo && cargo build --verbose
    - name: Run tests
      run: cd examples/demo && cargo test --verbose
